import { Country } from "@/types/country";
export const countries: Country[] = [
  {
    id: "afghanistan",
    flag: "🇦🇫",
    name: "Afghanistan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "akrotiri-sovereign-base-area",
    flag: "🏳️",
    name: "Akrotiri Sovereign Base Area",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "aland",
    flag: "🇦🇽",
    name: "Aland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "albania",
    flag: "🇦🇱",
    name: "Albania",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "algeria",
    flag: "🇩🇿",
    name: "Algeria",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "american-samoa",
    flag: "🇦🇸",
    name: "American Samoa",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "andorra",
    flag: "🇦🇩",
    name: "Andorra",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "angola",
    flag: "🇦🇴",
    name: "Angola",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "anguilla",
    flag: "🇦🇮",
    name: "Anguilla",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "antarctica",
    flag: "🇦🇶",
    name: "Antarctica",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "antigua-and-barbuda",
    flag: "🇦🇬",
    name: "Antigua and Barbuda",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "argentina",
    flag: "🇦🇷",
    name: "Argentina",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "armenia",
    flag: "🇦🇲",
    name: "Armenia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "aruba",
    flag: "🇦🇼",
    name: "Aruba",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ashmore-and-cartier-islands",
    flag: "🏳️",
    name: "Ashmore and Cartier Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "australia",
    flag: "🇦🇺",
    name: "Australia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "austria",
    flag: "🇦🇹",
    name: "Austria",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "azerbaijan",
    flag: "🇦🇿",
    name: "Azerbaijan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bahrain",
    flag: "🇧🇭",
    name: "Bahrain",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bajo-nuevo-bank-petrel-is",
    flag: "🏳️",
    name: "Bajo Nuevo Bank (Petrel Is.)",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bangladesh",
    flag: "🇧🇩",
    name: "Bangladesh",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "barbados",
    flag: "🇧🇧",
    name: "Barbados",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "baykonur-cosmodrome",
    flag: "🏳️",
    name: "Baykonur Cosmodrome",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "belarus",
    flag: "🇧🇾",
    name: "Belarus",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "belgium",
    flag: "🇧🇪",
    name: "Belgium",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "belize",
    flag: "🇧🇿",
    name: "Belize",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "benin",
    flag: "🇧🇯",
    name: "Benin",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bermuda",
    flag: "🇧🇲",
    name: "Bermuda",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bhutan",
    flag: "🇧🇹",
    name: "Bhutan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bir-tawil",
    flag: "🏳️",
    name: "Bir Tawil",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bolivia",
    flag: "🇧🇴",
    name: "Bolivia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bosnia-and-herzegovina",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "botswana",
    flag: "🇧🇼",
    name: "Botswana",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "brazil",
    flag: "🇧🇷",
    name: "Brazil",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "brazilian-island",
    flag: "🏳️",
    name: "Brazilian Island",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "british-indian-ocean-territory",
    flag: "🇮🇴",
    name: "British Indian Ocean Territory",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "british-virgin-islands",
    flag: "🇻🇬",
    name: "British Virgin Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "brunei",
    flag: "🇧🇳",
    name: "Brunei",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "bulgaria",
    flag: "🇧🇬",
    name: "Bulgaria",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "burkina-faso",
    flag: "🇧🇫",
    name: "Burkina Faso",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "burundi",
    flag: "🇧🇮",
    name: "Burundi",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cabo-verde",
    flag: "🇨🇻",
    name: "Cabo Verde",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cambodia",
    flag: "🇰🇭",
    name: "Cambodia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cameroon",
    flag: "🇨🇲",
    name: "Cameroon",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "canada",
    flag: "🇨🇦",
    name: "Canada",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cayman-islands",
    flag: "🇰🇾",
    name: "Cayman Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "central-african-republic",
    flag: "🇨🇫",
    name: "Central African Republic",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "chad",
    flag: "🇹🇩",
    name: "Chad",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "chile",
    flag: "🇨🇱",
    name: "Chile",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "china",
    flag: "🇨🇳",
    name: "China",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "clipperton-island",
    flag: "🏳️",
    name: "Clipperton Island",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "colombia",
    flag: "🇨🇴",
    name: "Colombia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "comoros",
    flag: "🇰🇲",
    name: "Comoros",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cook-islands",
    flag: "🇨🇰",
    name: "Cook Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "coral-sea-islands",
    flag: "🏳️",
    name: "Coral Sea Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "costa-rica",
    flag: "🇨🇷",
    name: "Costa Rica",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "croatia",
    flag: "🇭🇷",
    name: "Croatia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cuba",
    flag: "🇨🇺",
    name: "Cuba",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "curacao",
    flag: "🇨🇼",
    name: "Curaçao",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cyprus",
    flag: "🇨🇾",
    name: "Cyprus",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "cyprus-no-mans-area",
    flag: "🏳️",
    name: "Cyprus No Mans Area",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "czechia",
    flag: "🇨🇿",
    name: "Czechia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "democratic-republic-of-the-congo",
    flag: "🇨🇩",
    name: "Democratic Republic of the Congo",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "denmark",
    flag: "🇩🇰",
    name: "Denmark",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "dhekelia-sovereign-base-area",
    flag: "🏳️",
    name: "Dhekelia Sovereign Base Area",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "djibouti",
    flag: "🇩🇯",
    name: "Djibouti",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "dominica",
    flag: "🇩🇲",
    name: "Dominica",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "dominican-republic",
    flag: "🇩🇴",
    name: "Dominican Republic",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "east-timor",
    flag: "🇹🇱",
    name: "East Timor",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ecuador",
    flag: "🇪🇨",
    name: "Ecuador",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "egypt",
    flag: "🇪🇬",
    name: "Egypt",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "el-salvador",
    flag: "🇸🇻",
    name: "El Salvador",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "equatorial-guinea",
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "eritrea",
    flag: "🇪🇷",
    name: "Eritrea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "estonia",
    flag: "🇪🇪",
    name: "Estonia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ethiopia",
    flag: "🇪🇹",
    name: "Ethiopia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "falkland-islands",
    flag: "🇫🇰",
    name: "Falkland Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "faroe-islands",
    flag: "🇫🇴",
    name: "Faroe Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "federated-states-of-micronesia",
    flag: "🇫🇲",
    name: "Federated States of Micronesia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "fiji",
    flag: "🇫🇯",
    name: "Fiji",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "finland",
    flag: "🇫🇮",
    name: "Finland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "france",
    flag: "🏳️",
    name: "France",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "french-polynesia",
    flag: "🇵🇫",
    name: "French Polynesia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "french-southern-and-antarctic-lands",
    flag: "🇹🇫",
    name: "French Southern and Antarctic Lands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "gabon",
    flag: "🇬🇦",
    name: "Gabon",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "gambia",
    flag: "🇬🇲",
    name: "Gambia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "georgia",
    flag: "🇬🇪",
    name: "Georgia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "germany",
    flag: "🇩🇪",
    name: "Germany",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ghana",
    flag: "🇬🇭",
    name: "Ghana",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "gibraltar",
    flag: "🇬🇮",
    name: "Gibraltar",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "greece",
    flag: "🇬🇷",
    name: "Greece",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "greenland",
    flag: "🇬🇱",
    name: "Greenland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "grenada",
    flag: "🇬🇩",
    name: "Grenada",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guam",
    flag: "🇬🇺",
    name: "Guam",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guatemala",
    flag: "🇬🇹",
    name: "Guatemala",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guernsey",
    flag: "🇬🇬",
    name: "Guernsey",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guinea",
    flag: "🇬🇳",
    name: "Guinea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guinea-bissau",
    flag: "🇬🇼",
    name: "Guinea-Bissau",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "guyana",
    flag: "🇬🇾",
    name: "Guyana",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "haiti",
    flag: "🇭🇹",
    name: "Haiti",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "heard-island-and-mcdonald-islands",
    flag: "🇭🇲",
    name: "Heard Island and McDonald Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "honduras",
    flag: "🇭🇳",
    name: "Honduras",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "hong-kong-sar",
    flag: "🇭🇰",
    name: "Hong Kong S.A.R.",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "hungary",
    flag: "🇭🇺",
    name: "Hungary",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "iceland",
    flag: "🇮🇸",
    name: "Iceland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "india",
    flag: "🇮🇳",
    name: "India",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "indian-ocean-territories",
    flag: "🏳️",
    name: "Indian Ocean Territories",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "indonesia",
    flag: "🇮🇩",
    name: "Indonesia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "iran",
    flag: "🇮🇷",
    name: "Iran",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "iraq",
    flag: "🇮🇶",
    name: "Iraq",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ireland",
    flag: "🇮🇪",
    name: "Ireland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "isle-of-man",
    flag: "🇮🇲",
    name: "Isle of Man",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "israel",
    flag: "🇮🇱",
    name: "Israel",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "italy",
    flag: "🇮🇹",
    name: "Italy",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ivory-coast",
    flag: "🇨🇮",
    name: "Ivory Coast",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "jamaica",
    flag: "🇯🇲",
    name: "Jamaica",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "japan",
    flag: "🇯🇵",
    name: "Japan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "jersey",
    flag: "🇯🇪",
    name: "Jersey",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "jordan",
    flag: "🇯🇴",
    name: "Jordan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kazakhstan",
    flag: "🇰🇿",
    name: "Kazakhstan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kenya",
    flag: "🇰🇪",
    name: "Kenya",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kiribati",
    flag: "🇰🇮",
    name: "Kiribati",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kosovo",
    flag: "🏳️",
    name: "Kosovo",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kuwait",
    flag: "🇰🇼",
    name: "Kuwait",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "kyrgyzstan",
    flag: "🇰🇬",
    name: "Kyrgyzstan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "laos",
    flag: "🇱🇦",
    name: "Laos",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "latvia",
    flag: "🇱🇻",
    name: "Latvia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "lebanon",
    flag: "🇱🇧",
    name: "Lebanon",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "lesotho",
    flag: "🇱🇸",
    name: "Lesotho",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "liberia",
    flag: "🇱🇷",
    name: "Liberia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "libya",
    flag: "🇱🇾",
    name: "Libya",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "liechtenstein",
    flag: "🇱🇮",
    name: "Liechtenstein",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "lithuania",
    flag: "🇱🇹",
    name: "Lithuania",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "luxembourg",
    flag: "🇱🇺",
    name: "Luxembourg",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "macao-sar",
    flag: "🇲🇴",
    name: "Macao S.A.R",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "madagascar",
    flag: "🇲🇬",
    name: "Madagascar",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "malawi",
    flag: "🇲🇼",
    name: "Malawi",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "malaysia",
    flag: "🇲🇾",
    name: "Malaysia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "maldives",
    flag: "🇲🇻",
    name: "Maldives",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mali",
    flag: "🇲🇱",
    name: "Mali",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "malta",
    flag: "🇲🇹",
    name: "Malta",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "marshall-islands",
    flag: "🇲🇭",
    name: "Marshall Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mauritania",
    flag: "🇲🇷",
    name: "Mauritania",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mauritius",
    flag: "🇲🇺",
    name: "Mauritius",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mexico",
    flag: "🇲🇽",
    name: "Mexico",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "moldova",
    flag: "🇲🇩",
    name: "Moldova",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "monaco",
    flag: "🇲🇨",
    name: "Monaco",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mongolia",
    flag: "🇲🇳",
    name: "Mongolia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "montenegro",
    flag: "🇲🇪",
    name: "Montenegro",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "montserrat",
    flag: "🇲🇸",
    name: "Montserrat",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "morocco",
    flag: "🇲🇦",
    name: "Morocco",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "mozambique",
    flag: "🇲🇿",
    name: "Mozambique",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "myanmar",
    flag: "🇲🇲",
    name: "Myanmar",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "namibia",
    flag: "🇳🇦",
    name: "Namibia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "nauru",
    flag: "🇳🇷",
    name: "Nauru",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "nepal",
    flag: "🇳🇵",
    name: "Nepal",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "netherlands",
    flag: "🇳🇱",
    name: "Netherlands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "new-caledonia",
    flag: "🇳🇨",
    name: "New Caledonia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "new-zealand",
    flag: "🇳🇿",
    name: "New Zealand",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "nicaragua",
    flag: "🇳🇮",
    name: "Nicaragua",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "niger",
    flag: "🇳🇪",
    name: "Niger",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "nigeria",
    flag: "🇳🇬",
    name: "Nigeria",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "niue",
    flag: "🇳🇺",
    name: "Niue",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "norfolk-island",
    flag: "🇳🇫",
    name: "Norfolk Island",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "north-korea",
    flag: "🇰🇵",
    name: "North Korea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "north-macedonia",
    flag: "🇲🇰",
    name: "North Macedonia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "northern-cyprus",
    flag: "🏳️",
    name: "Northern Cyprus",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "northern-mariana-islands",
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "norway",
    flag: "🏳️",
    name: "Norway",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "oman",
    flag: "🇴🇲",
    name: "Oman",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "pakistan",
    flag: "🇵🇰",
    name: "Pakistan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "palau",
    flag: "🇵🇼",
    name: "Palau",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "palestine",
    flag: "🇵🇸",
    name: "Palestine",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "panama",
    flag: "🇵🇦",
    name: "Panama",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "papua-new-guinea",
    flag: "🇵🇬",
    name: "Papua New Guinea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "paraguay",
    flag: "🇵🇾",
    name: "Paraguay",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "peru",
    flag: "🇵🇪",
    name: "Peru",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "philippines",
    flag: "🇵🇭",
    name: "Philippines",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "pitcairn-islands",
    flag: "🇵🇳",
    name: "Pitcairn Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "poland",
    flag: "🇵🇱",
    name: "Poland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "portugal",
    flag: "🇵🇹",
    name: "Portugal",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "puerto-rico",
    flag: "🇵🇷",
    name: "Puerto Rico",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "qatar",
    flag: "🇶🇦",
    name: "Qatar",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "republic-of-serbia",
    flag: "🇷🇸",
    name: "Republic of Serbia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "republic-of-the-congo",
    flag: "🇨🇬",
    name: "Republic of the Congo",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "romania",
    flag: "🇷🇴",
    name: "Romania",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "russia",
    flag: "🇷🇺",
    name: "Russia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "rwanda",
    flag: "🇷🇼",
    name: "Rwanda",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-barthelemy",
    flag: "🇧🇱",
    name: "Saint Barthelemy",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-helena",
    flag: "🇸🇭",
    name: "Saint Helena",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-kitts-and-nevis",
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-lucia",
    flag: "🇱🇨",
    name: "Saint Lucia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-martin",
    flag: "🇲🇫",
    name: "Saint Martin",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-pierre-and-miquelon",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saint-vincent-and-the-grenadines",
    flag: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "samoa",
    flag: "🇼🇸",
    name: "Samoa",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "san-marino",
    flag: "🇸🇲",
    name: "San Marino",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "saudi-arabia",
    flag: "🇸🇦",
    name: "Saudi Arabia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "scarborough-reef",
    flag: "🏳️",
    name: "Scarborough Reef",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "senegal",
    flag: "🇸🇳",
    name: "Senegal",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "serranilla-bank",
    flag: "🏳️",
    name: "Serranilla Bank",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "seychelles",
    flag: "🇸🇨",
    name: "Seychelles",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "siachen-glacier",
    flag: "🏳️",
    name: "Siachen Glacier",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sierra-leone",
    flag: "🇸🇱",
    name: "Sierra Leone",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "singapore",
    flag: "🇸🇬",
    name: "Singapore",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sint-maarten",
    flag: "🇸🇽",
    name: "Sint Maarten",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "slovakia",
    flag: "🇸🇰",
    name: "Slovakia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "slovenia",
    flag: "🇸🇮",
    name: "Slovenia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "solomon-islands",
    flag: "🇸🇧",
    name: "Solomon Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "somalia",
    flag: "🇸🇴",
    name: "Somalia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "somaliland",
    flag: "🏳️",
    name: "Somaliland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "south-africa",
    flag: "🇿🇦",
    name: "South Africa",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "south-georgia-and-the-islands",
    flag: "🇬🇸",
    name: "South Georgia and the Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "south-korea",
    flag: "🇰🇷",
    name: "South Korea",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "south-sudan",
    flag: "🇸🇸",
    name: "South Sudan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "southern-patagonian-ice-field",
    flag: "🏳️",
    name: "Southern Patagonian Ice Field",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "spain",
    flag: "🇪🇸",
    name: "Spain",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "spratly-islands",
    flag: "🏳️",
    name: "Spratly Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sri-lanka",
    flag: "🇱🇰",
    name: "Sri Lanka",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sudan",
    flag: "🇸🇩",
    name: "Sudan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "suriname",
    flag: "🇸🇷",
    name: "Suriname",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sweden",
    flag: "🇸🇪",
    name: "Sweden",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "switzerland",
    flag: "🇨🇭",
    name: "Switzerland",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "syria",
    flag: "🇸🇾",
    name: "Syria",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "sao-tome-and-principe",
    flag: "🇸🇹",
    name: "São Tomé and Principe",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "taiwan",
    flag: "🏳️",
    name: "Taiwan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "tajikistan",
    flag: "🇹🇯",
    name: "Tajikistan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "thailand",
    flag: "🇹🇭",
    name: "Thailand",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "the-bahamas",
    flag: "🇧🇸",
    name: "The Bahamas",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "togo",
    flag: "🇹🇬",
    name: "Togo",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "tonga",
    flag: "🇹🇴",
    name: "Tonga",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "trinidad-and-tobago",
    flag: "🇹🇹",
    name: "Trinidad and Tobago",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "tunisia",
    flag: "🇹🇳",
    name: "Tunisia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "turkey",
    flag: "🇹🇷",
    name: "Turkey",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "turkmenistan",
    flag: "🇹🇲",
    name: "Turkmenistan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "turks-and-caicos-islands",
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "tuvalu",
    flag: "🇹🇻",
    name: "Tuvalu",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "us-naval-base-guantanamo-bay",
    flag: "🏳️",
    name: "US Naval Base Guantanamo Bay",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "uganda",
    flag: "🇺🇬",
    name: "Uganda",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "ukraine",
    flag: "🇺🇦",
    name: "Ukraine",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-arab-emirates",
    flag: "🇦🇪",
    name: "United Arab Emirates",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-kingdom",
    flag: "🇬🇧",
    name: "United Kingdom",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-republic-of-tanzania",
    flag: "🇹🇿",
    name: "United Republic of Tanzania",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-states-minor-outlying-islands",
    flag: "🇺🇲",
    name: "United States Minor Outlying Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-states-virgin-islands",
    flag: "🇻🇮",
    name: "United States Virgin Islands",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "united-states-of-america",
    flag: "🇺🇸",
    name: "United States of America",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "uruguay",
    flag: "🇺🇾",
    name: "Uruguay",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "uzbekistan",
    flag: "🇺🇿",
    name: "Uzbekistan",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "vanuatu",
    flag: "🇻🇺",
    name: "Vanuatu",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "vatican",
    flag: "🇻🇦",
    name: "Vatican",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "venezuela",
    flag: "🇻🇪",
    name: "Venezuela",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "vietnam",
    flag: "🇻🇳",
    name: "Vietnam",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "wallis-and-futuna",
    flag: "🇼🇫",
    name: "Wallis and Futuna",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "western-sahara",
    flag: "🇪🇭",
    name: "Western Sahara",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "yemen",
    flag: "🇾🇪",
    name: "Yemen",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "zambia",
    flag: "🇿🇲",
    name: "Zambia",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "zimbabwe",
    flag: "🇿🇼",
    name: "Zimbabwe",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
  {
    id: "eswatini",
    flag: "🇸🇿",
    name: "eSwatini",
    image: "/images/countries/default.jpg",
    lawrence: false,
    ciara: false,
  },
];
